### ISSUE TITLE
Support enforce pre?

### ISSUE THREAD

**Issue by yunsii** [unplugin/unplugin-auto-import#424]
### Clear and concise description of the problem

Like https://lingui.dev/ref/swc-plugin it will transform source code too, so If I auto import somethings from `@lingui/macro`, this plugin should transform before `@lingui/swc-plugin`.

### Suggested solution

Support enforce pre, I try to patch this package from "post" to "pre", but it not work directly.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
I think we can have an option
https://github.com/sxzz/unplugin-starter/blob/9430d6f711437b2760832e18fbae7b14bce2e615/src/core/options.ts#L20

**Comment by antfu** [comment]
I honestly don't think it's about exposing an option or not. The problem is that this plugin is built with the assumption the input is transpiled JS, meaning we don't handle any specific syntax liks TS, JSX, Vue, etc. And honestly, we are unlikely would do so as they will introduce more caveats. As you mentioned the patching does not work, which also indicates that.

I'd say this plugin is not designed for runtime import, but not for macros. I'd suggest you find your own way for the macro, or make it runs after this plugin (but still need to be `post`)

**Comment by antfu** [comment]
> why this plugin is not designed for runtime import? 

Oh, it was a typo. I mean **only**. 😅

> it will use babel or something else to parse sourcecode, and significantly increased compilation time?

I believe using Babel will indeed help with the accuracy, but we don't have interests in doing this refactor. Maybe it can be another plugin if you have vital requirements.

**Comment by yunsii** [comment]
I see, maybe I can have a try.
