### ISSUE TITLE
Add `@mdi/js` preset

### ISSUE THREAD

**Issue by 0x00A1FA** [unplugin/unplugin-auto-import#446]
### Clear and concise description of the problem

Adding auto import capabilities for the `@mdi/js` package.

### Suggested solution

Add all icons from `@mdi/js` in the `auto-imports.d.ts` file.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by userquin** [comment]
something like this?

![imagen](https://github.com/unplugin/unplugin-auto-import/assets/6311119/796344cc-b459-4ec8-97dd-c0218e056b38)


![imagen](https://github.com/unplugin/unplugin-auto-import/assets/6311119/6c70b891-b2a4-4689-851a-c10c6ff26b5b)

**Comment by antfu** [comment]
https://github.com/unplugin/unplugin-auto-import/pull/450#issuecomment-1826180192

**Comment by userquin** [comment]
@0x00A1FA you can add `packagePresets: ['@mdi/js'],` to your `unplugin-auto-import` plugin configuration with latest release `v0.17.2`:
- if using type module in your project, you can use [mdi-js-es](https://github.com/userquin/mdi-js-es) package (`@mdi/js` resolves to CJS and will not work):  check this issue https://github.com/Templarian/MaterialDesign-JS/issues/28, next version of `@mdi/js` should fix it
- otherwise you can try with `@mdi/js`
